// ---------------------------------------------------------------------------
#ifndef DP_RepStringsH
#define DP_RepStringsH
// ---------------------------------------------------------------------------

#define IDS_COPYRIGHT					0001
#define IDS_COPYRIGHT_STATUS			0002

#define IDS_QUESTION_CLOSE_PROGRAM		0100
#define IDS_QUESTION_SETTINGS_CHANGED	0101
#define IDS_QUESTION_DB_DROP			0102
#define IDS_QUESTION_DB_CREATE			0103
#define IDS_QUESTION_TRAIN_CHANGED		0104

#define IDS_ERROR_UNKNOWN				0200
#define IDS_ERROR_SETTINGS_SAVE			0201
#define IDS_ERROR_NEED_USERNAME			0202
#define IDS_ERROR_SELECT_USERNAME		0203
#define IDS_ERROR_PASS_WRONG			0204
#define IDS_ERROR_USERS_LAST_ADMIN		0205
#define IDS_ERROR_MYSQL_CONNECTION      0250
#define IDS_ERROR_MYSQL_DB_DROP      	0251
#define IDS_ERROR_MYSQL_DB_CREATE      	0252

#define IDS_MSG_MYSQL_CONNECTION_OK 	0300
#define IDS_MSG_MYSQL_DB_DROP_OK 		0301
#define IDS_MSG_MYSQL_DB_CREATE_OK 		0302

#define IDS_TXT_ADMIN_DEFAULT_NAME		0400

#define IDS_MYSQL_CONNECTION			3000
#define IDS_MYSQL_VERSION				3001
#define IDS_MYSQL_DATABASE_DROP			3002
#define IDS_MYSQL_DATABASE_CREATE		3003
#define IDS_MYSQL_TBL_TRAINS_CREATE		3004
#define IDS_MYSQL_TBL_VANS_CREATE		3005

#define IDS_LOG_START_PROGRAM			9001
#define IDS_LOG_STOP_PROGRAM			9002
#define IDS_LOG_OPTIONS_SAVE			9003
#define IDS_LOG_OPTIONS_CANCEL			9004
#define IDS_LOG_LOGIN_OK				9005
#define IDS_LOG_LOGIN_CANCEL			9006
#define IDS_LOG_CREATE_DIR_FAIL			9010
#define IDS_LOG_WRITE_FILE_FAIL			9011
#define IDS_LOG_READ_FILE_FAIL			9012
#define IDS_LOG_MYSQL_CONNECT			9100
#define IDS_LOG_MYSQL_CONNECT_OK		9101
#define IDS_LOG_MYSQL_CONNECT_FAIL		9102
#define IDS_LOG_MYSQL_DB_DROP_OK  		9103
#define IDS_LOG_MYSQL_DB_DROP_FAIL		9104
#define IDS_LOG_MYSQL_DB_CREATE_OK		9105
#define IDS_LOG_MYSQL_DB_CREATE_FAIL	9106
#define IDS_LOG_MYSQL_SAVE_TRAIN_OK		9107
#define IDS_LOG_MYSQL_SAVE_TRAIN_FAIL	9108

// ---------------------------------------------------------------------------
#endif
