CREATE TABLE vans
(
  trnum                  INT(10) UNSIGNED                           NOT NULL,
  scales                 INT(10) DEFAULT '0'                        NOT NULL,
  num                    SMALLINT(5) UNSIGNED                       NOT NULL,
  wtime                  INT(10) UNSIGNED                           NOT NULL,
  bdatetime              DATETIME DEFAULT '0000-00-00 00:00:00'     NULL,
  vannum                 CHAR(8)                                    NULL,
  vantype                CHAR(32)                                   NULL,
  vantype_code           INT(10)                                    NULL,
  carrying               INT(10) UNSIGNED DEFAULT 0                 NULL,
  brutto                 INT(10) UNSIGNED DEFAULT 0                 NULL,
  tare                   INT(10) UNSIGNED DEFAULT 0                 NULL,
  tare_t                 INT(10) UNSIGNED DEFAULT 0                 NULL,
  tare_d                 INT(10) UNSIGNED DEFAULT 0                 NULL,
  tare_s                 INT(10) UNSIGNED DEFAULT 0                 NULL,
  tareindex              SMALLINT UNSIGNED DEFAULT 0                NOT NULL,
  iscales_tare           INT(10) DEFAULT 0                          NOT NULL,
  idatetime_tare         DATETIME DEFAULT '0000-00-00 00:00:00'     NULL,
  netto                  INT(10) DEFAULT 0                          NULL,
  overload               INT(10) DEFAULT 0                          NULL,
  cargotype              CHAR(32) DEFAULT ''                        NULL,
  cargotype_code         CHAR(10)                                   NULL,
  naxis                  SMALLINT(5) UNSIGNED DEFAULT 0             NOT NULL,
  operator_name          CHAR(24)                                   NULL,
  operator_tabn          CHAR(8)                                    NULL,
  operator_shift         CHAR(4)                                    NULL,
  depart_station         CHAR(32)                                   NULL,
  depart_station_code    CHAR(7)                                    NULL,
  purpose_station        CHAR(32)                                   NULL,
  purpose_station_code   CHAR(7)                                    NULL,
  invoice_num            CHAR(16) DEFAULT ''                        NULL,
  invoice_supplier       CHAR(32)                                   NULL,
  invoice_supplier_code  CHAR(7)                                    NULL,
  invoice_recipient      CHAR(32)                                   NULL,
  invoice_recipient_code CHAR(7)                                    NULL,
  invoice_tare           INT(10)UNSIGNED DEFAULT 0                  NULL,
  invoice_netto          INT(10)UNSIGNED DEFAULT 0                  NULL,

  PRIMARY KEY (trnum, num, scales)
)
  ENGINE = MyISAM;
